<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Views\Components\AllPortions;
use Miklcct\NationalRailTimetable\Views\Components\Portion;

/** @var AllPortions $this */
?>
<table class="portion">
<?php
foreach ($this->portions as $segment) {
?>
    <tr>
        <td>
            <table class="portion">
                <tr>
<?php
    foreach ($segment as $i => $portion) {
?>
                    <td>
<?php
        if ($i === 0) {
            echo new Portion($this->getStreamFactory(), $this->dateFromOrigin, $portion['dated_service'], array_diff_key($portion, ['dated_service' => null]), $this->permanentOnly);
        } else {
            echo new AllPortions($this->getStreamFactory(), $this->dateFromOrigin, $portion, $this->permanentOnly);
        }
?>
                    </td>
<?php
    }
?>
                </tr>
            </table>
        </td>
    </tr>
<?php
}
?>
</table>
<?php
