<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Enums\Activity;
use Miklcct\NationalRailTimetable\Models\LocationWithCrs;
use Miklcct\NationalRailTimetable\Models\ServiceCallWithDestination;
use Miklcct\NationalRailTimetable\Models\Station;
use Miklcct\NationalRailTimetable\Views\BoardFormView;
use Miklcct\NationalRailTimetable\Views\BoardView;
use Miklcct\NationalRailTimetable\Views\ServiceView;
use function Miklcct\NationalRailTimetable\Views\show_time;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var BoardFormView $this */
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="common.css" />
        <link rel="stylesheet" href="board.css" />
        <title><?= html($this->getTitle()) ?></title>
        <script defer="defer" src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
        <script defer="defer" src="/board.js"></script>
    </head>
    <body>
        <button id="go_to_top">🔝</button>
<?php
require __DIR__ . '/form.phtml';

if ($this instanceof BoardView) {
    $view = $this;
?>  
        <h1><?= html($this->getHeading()) ?></h1>
<?php
    $query = $this->query;
    if (count($query->filter) === 1) {
?>

        <p><a href="<?= $this->getReverseDirectionLink() ?>">Show return departure board</a></p>
<?php
    }
    if ($query->permanentOnly) {
?>
        <p id="permanent_warning">Warning: Permanent timetable instead of actual timetable shown</p>
<?php
    }
    $station = $query->station;
    if ($station instanceof Station) {
?>
        <p>Minimum connection time is <span class="time"><?= html(
                    $station->minimumConnectionTime . ($station->minimumConnectionTime === 1 ? ' minute' : ' minutes')) ?></span><?= $station->tocConnectionTimes === [] ? '.' : ', with the exception of the following:' ?></p>
<?php
        if ($station->tocConnectionTimes !== []) {
?>
        <table>
            <thead>
                <tr><th>From</th><th>To</th><th>Minutes</th></tr>
            </thead>
            <tbody>
<?php
            foreach ($station->tocConnectionTimes as $entry) {
?>
                <tr>
                    <td><?= $this->showToc($entry->arrivingToc) ?></td>
                    <td><?= $this->showToc($entry->departingToc) ?></td>
                    <td><?= html($entry->connectionTime) ?></td>
                </tr>
<?php
            }
?>
            </tbody>
        </table>
<?php
        }

        if (!empty($this->fixedLinks)) {
?>
        <table>
            <thead>
                <tr><th colspan="6">
                    Fixed links 
                    <?= html(
                        $this->fixedLinkDepartureTime !== null 
                        ? 'as of ' . $this->fixedLinkDepartureTime->format('Y-m-d H:i') 
                        : 'on ' . $this->boardDate) 
                    ?>
                </th></tr>
                <tr>
                    <th>Transfer to</th>
                    <th>Mode</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Minutes</th>
<?php
            if ($this->fixedLinkDepartureTime !== null) {
?>
                    <th><?= $query->arrivalMode ? 'Departure' : 'Arrival' ?></th>
<?php
            }
?>
                </tr>
            </thead>
            <tbody>
<?php
            foreach ($this->fixedLinks as $link) {
                if ($this->fixedLinkDepartureTime) {
                    $kgx_hack = $station->crsCode === 'KGX' && $link->destination->crsCode === 'STP'
                        || $station->crsCode === 'STP' && $link->destination->crsCode === 'KGX';
                    $departure_time = $kgx_hack && $query->connectingTime !== null
                        ? $query->arrivalMode ? $query->connectingTime->sub(new DateInterval('PT5M')) : $query->connectingTime->add(new DateInterval('PT5M'))
                        : $this->fixedLinkDepartureTime;
                    $arrival_time = $link->getArrivalTime($departure_time, $query->arrivalMode);
                }
?>
                <tr>
                    <td class="destination">
                        <a href="<?= html($this->getFixedLinkUrl($link, $departure_time ?? null)) ?>">
                            <?= html($link->destination->getShortName()) ?>
                        </a>
                    </td>
                    <td><?= html($link->mode) ?></td>
                    <td><?= html($link->startTime) ?></td>
                    <td><?= html($link->endTime) ?></td>
                    <td><?= html($link->transferTime) ?></td>
<?php
                if ($this->fixedLinkDepartureTime !== null) {
?>
                    <td class="time"><?= show_time($arrival_time, $this->boardDate) ?></td>
<?php
                }
?>
                </tr>
<?php
            }
?>
            </tbody>
        </table>
<?php
        }
    }
?>
        <table>
            <thead>
<?php
    if ($query->arrivalMode) {
?>
                <tr><th colspan="7"><a href="<?= $this->getDayOffsetLink(1) ?>">Next day</a></th></tr>
<?php
    } else {
?>
                <tr><th colspan="7"><a href="<?= $this->getDayOffsetLink(-1) ?>">Previous day</a></th></tr>
<?php
    }
?>
                <tr>
                    <th>Time</th>
                    <th></th>
                    <th>Pl.</th>
                    <th>TOC</th>
                    <th>Train no.</th>
                    <th><?= $query->arrivalMode ? 'Origin' : 'Destination' ?></th>
                    <th>Calling at</th>
                </tr>
            </thead>
            <tfoot>
<?php
    if ($query->arrivalMode) {
?>
               <tr><th colspan="7"><a href="<?= $this->getDayOffsetLink(-1) ?>">Previous day</a></th></tr>
<?php
    } else {
?>
               <tr><th colspan="7"><a href="<?= $this->getDayOffsetLink(1) ?>">Next day</a></th></tr>
<?php
    }
?>
            </tfoot>
            <tbody>
<?php
    $previous_timestamp = null;
    foreach ($query->arrivalMode ? array_reverse($this->board->calls, true) : $this->board->calls as $service_call) {
        $timestamp = $service_call->timestamp;
        $destinations = $query->arrivalMode ? $service_call->origins : $service_call->destinations;
        $portions_count = count($destinations);
        $portion_uids = array_keys($destinations);
        $overtaken_portions = array_combine(
            $portion_uids
            , array_map(
                fn(string $uid) : bool => count($query->filter) === 1 ? $view->board->isOvertaken($service_call, $query->filter[0]->getCrsCode(), $uid) : false
                , $portion_uids
            )
        );
        $whole_train_overtaken = !in_array(false, $overtaken_portions, true);
        $day_offset = $timestamp->setTime(0, 0)->diff($this->boardDate->toDateTimeImmutable())->days;
?>
                <tr data-timestamp="<?= html($timestamp->getTimestamp()) ?>">
                    <td class="time <?= 
                        $query->connectingTime === null || !$station instanceof Station
                            ? '' 
                            : ($service_call->isValidConnection($query->connectingTime, $this->connectingToc ?? null) ? 'valid_connection' : 'invalid_connection')
                    ?> <?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>">
                        <?= 
                            show_time($timestamp, $this->boardDate, ServiceView::getServiceUrl($service_call->uid, $service_call->date, $query->permanentOnly))
                            . (in_array(Activity::REQUEST_STOP, $service_call->call->activities, true) ? '<abbr title="request stop">x</abbr>' : '')
                        ?>
                    </td>
                    <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= $this->showFacilities($service_call) ?></td>
                    <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= html($service_call->call->platform) ?></td>
                    <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= $this->showToc($service_call->toc) ?></td>
                    <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><a href="<?= html(ServiceView::getServiceUrl($service_call->uid, $service_call->date, $query->permanentOnly)) ?>"><?= html(substr($service_call->serviceProperty->rsid, 0, 6)) ?></a></td>
<?php
        foreach ($portion_uids as $i => $uid) {
            if ($i > 0) {
?>
                </tr>
                <tr>
<?php
            }
?>
                    <td class="destination <?= $overtaken_portions[$uid] ? 'overtaken' : '' ?>"><?= html($destinations[$uid]->location->getShortName()) ?></td>
                    <td class="<?= $overtaken_portions[$uid] ? 'overtaken' : '' ?>"><?=                        
                        implode(
                            ', '
                            , array_map(
                                static function(ServiceCallWithDestination $service_call) use ($view): string {
                                    $station = $service_call->call->location;
                                    $link = $view->getArrivalLink($service_call);
                                    return sprintf(
                                        $link === null ? '<span class="%1$s">%3$s (%4$s%5$s)</span>' : '<span class="%s"><a href="%s">%s</a> (%s%s)</span>'
                                        , $station instanceof LocationWithCrs && in_array($station->getCrsCode(), array_map(static fn(LocationWithCrs $destination) => $destination->getCrsCode(), $view->query->filter), true) ? 'destination' : ''
                                        , html($link)
                                        , html($station->getShortName())
                                        , show_time($service_call->timestamp, $view->boardDate)
                                        , in_array(Activity::REQUEST_STOP, $service_call->call->activities, true) ? '<abbr title="request stop">x</abbr>' : ''
                                    );
                                }
                                , array_filter(
                                    $query->arrivalMode ? $service_call->precedingCalls : $service_call->subsequentCalls
                                    , fn(ServiceCallWithDestination $service_call) : bool => array_key_exists(
                                    $uid,
                                    $this->query->arrivalMode ? $service_call->origins : $service_call->destinations
                                )
                                )
                            )
                        )
                    ?></td>
<?php
        }
?>
                </tr>
<?php
        $previous_timestamp = $timestamp;
    }
?>
            </tbody>
        </table>
        <footer>
            Data updated: <?= $this->generated ?>
        </footer>
<?php
}
?>
    </body>
</html>