<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Views\BoardFormView;
use Miklcct\NationalRailTimetable\Views\BoardView;
use Miklcct\NationalRailTimetable\Models\FixedLink;
use Miklcct\NationalRailTimetable\Enums\Activity;
use Miklcct\NationalRailTimetable\Models\Station;
use Miklcct\NationalRailTimetable\Models\Location;
use Miklcct\NationalRailTimetable\Models\ServiceCallWithDestination;

use function Miklcct\NationalRailTimetable\get_all_tocs;
use function Miklcct\NationalRailTimetable\show_time;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var BoardFormView $this */
?>
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="board.css" />
        <title><?= html($this->getTitle()) ?></title>
        <script defer="defer" src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
        <script defer="defer" src="/board.js"></script>
    </head>
    <body>
        <button id="go_to_top">🔝</button>
    <form action="<?= html($this->boardUrl) ?>" method="GET">
            <datalist id="stations">
<?php
/** @var Location */
foreach ($this->stations as $station) {
?>
                <option value="<?= html($station->crsCode) ?>"><?= html($station->name) ?></option>
<?php
}
?>
            </datalist>
            <p>
                Show 
<?php
foreach (['departures', 'arrivals'] as $mode) {
?>
                <label>
                    <input type="radio" name="mode" value="<?= html($mode) ?>" <?= ($this->getFormData()['mode'] ?? 'departures') === $mode ? 'checked = "checked"' : ''?>/>
                    <?= html($mode) ?>
                </label>
<?php
}
?>
                <label>at: <input autocomplete="off" list="stations" required="required" type="text" name="station" size="32" value="<?= html($this->getFormData()['station'] ?? null)?>"/></label><br/>
                <label>only trains calling at (optional): <input autocomplete="off" list="stations" type="text" name="filter" size="32" value="<?= html($this->getFormData()['filter'] ?? null) ?>"/></label><br/>
                <label>on (leave empty for today) <input type="date" name="date" value="<?= html($this->getFormData()['date'] ?? null) ?>"/></label>
            </p>
            <p>
                <label>Show valid connections at: <input type="datetime-local" name="connecting_time" value="<?= html($this->getFormData()['connecting_time'] ?? null) ?>"/>
                from TOC: <select name="connecting_toc">
                    <option></option>
<?php
/** @var Location */
foreach (get_all_tocs() as $code => $name) {
?>
                    <option value="<?= html($code) ?>" <?= $code === ($this->getFormData()['connecting_toc'] ?? null) ? 'selected="selected"' : '' ?>><?= html($name) ?></option>
<?php
}
?>
                </select></label></br>
            </p>
            <p>
                <label>Show permanent timetable instead of actual timetable: <input type="checkbox" name="permanent_only" <?= !empty($this->getFormData()['permanent_only']) ? 'checked="checked"' : '' ?>/></label><br/>
            </p>
            <p>
                <input type="submit" />
            </p>
        </form>
<?php
if ($this instanceof BoardView) {
?>  
        <h1><?= html($this->getHeading()) ?></h1>
<?php
    if ($this->permanentOnly) {
?>
        <p id="permanent_warning">Warning: Permanent timetable instead of actual timetable shown</p>
<?php
    }
    if ($this->station instanceof Station) {
?>
        <p>Minimum connection time is <span class="time"><?= html($this->station->minimumConnectionTime . ($this->station->minimumConnectionTime === 1 ? ' minute' : ' minutes')) ?></span><?= $this->station->tocConnectionTimes === [] ? '.' : ', with the exception of the following:' ?></p>
<?php
        if ($this->station->tocConnectionTimes !== []) {
?>
        <table>
            <thead>
                <tr><th>From</th><th>To</th><th>Minutes</th></tr>
            </thead>
            <tbody>
<?php
            foreach ($this->station->tocConnectionTimes as $entry) {
?>
                <tr>
                    <td><?= $this->showToc($entry->arrivingToc) ?></td>
                    <td><?= $this->showToc($entry->departingToc) ?></td>
                    <td><?= html($entry->connectionTime) ?></td>
                </tr>
<?php
            }
?>
            </tbody>
        </table>
<?php
        }

        if (!empty($this->fixedLinks)) {
?>
        <table>
            <thead>
                <tr><th colspan="6">
                    Fixed links 
                    <?= html(
                        $this->fixedLinkDepartureTime !== null 
                        ? 'as of ' . $this->fixedLinkDepartureTime->format('Y-m-d H:i') 
                        : 'on ' . $this->boardDate) 
                    ?>
                </th></tr>
                <tr>
                    <th>Transfer to</th>
                    <th>Mode</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Minutes</th>
<?php
            if ($this->fixedLinkDepartureTime !== null) {
?>
                    <th><?= $this->arrivalMode ? 'Departure' : 'Arrival' ?></th>
<?php
            }
?>
                </tr>
            </thead>
            <tbody>
<?php
            /** @var FixedLink */
            foreach ($this->fixedLinks as $link) {
                if ($this->fixedLinkDepartureTime) {
                    $kgx_hack = $this->station->crsCode === 'KGX' && $link->destination->crsCode === 'STP'
                        || $this->station->crsCode === 'STP' && $link->destination->crsCode === 'KGX';
                    $departure_time = $kgx_hack && $this->connectingTime !== null
                        ? $this->arrivalMode ? $this->connectingTime->sub(new DateInterval('PT5M')) : $this->connectingTime->add(new DateInterval('PT5M'))
                        : $this->fixedLinkDepartureTime;
                    $arrival_time = $link->getArrivalTime($departure_time, $this->arrivalMode);
                }
?>
                <tr>
                    <td class="destination">
                        <a href="<?= html($this->getFixedLinkUrl($link, $departure_time ?? null)) ?>">
                            <?= html($link->destination->getShortName()) ?>
                        </a>
                    </td>
                    <td><?= html($link->mode) ?></td>
                    <td><?= html($link->startTime) ?></td>
                    <td><?= html($link->endTime) ?></td>
                    <td><?= html($link->transferTime) ?></td>
<?php
                if ($this->fixedLinkDepartureTime !== null) {
?>
                    <td class="time"><?= show_time($arrival_time, $this->boardDate) ?></td>
<?php
                }
?>
                </tr>
<?php
            }
?>
            </tbody>
        </table>
<?php
        }
    }
?>
        <table>
            <thead>
<?php
    if ($this->arrivalMode) {
?>
                <tr><th colspan="7"><a href="<?= $this->getDayOffsetLink(1) ?>">Next day</a></th></tr>
<?php
    } else {
?>
                <tr><th colspan="7"><a href="<?= $this->getDayOffsetLink(-1) ?>">Previous day</a></th></tr>
<?php
    }
?>
                <tr>
                    <th>Time</th>
                    <th></th>
                    <th>Pl.</th>
                    <th>TOC</th>
                    <th>Train no.</th>
                    <th><?= $this->arrivalMode ? 'Origin' : 'Destination' ?></th>
                    <th>Calling at</th>
                </tr>
            </thead>
            <tfoot>
<?php
    if ($this->arrivalMode) {
?>
               <tr><th colspan="7"><a href="<?= $this->getDayOffsetLink(-1) ?>">Previous day</a></th></tr>
<?php
    } else {
?>
               <tr><th colspan="7"><a href="<?= $this->getDayOffsetLink(1) ?>">Next day</a></th></tr>
<?php
    }
?>
            </tfoot>
            <tbody>
<?php
    $previous_timestamp = null;
    foreach ($this->arrivalMode ? array_reverse($this->board->calls, true) : $this->board->calls as $service_call) {
        $timestamp = $service_call->timestamp;
        $destinations = $this->arrivalMode ? $service_call->origins : $service_call->destinations;
        $portions_count = count($destinations);
        $portion_uids = array_keys($destinations);
        $overtaken_portions = array_combine(
            $portion_uids
            , array_map(
                fn(string $uid) : bool => $this->destination !== null ? $this->board->isOvertaken($service_call, $this->destination->crsCode, $uid) : false
                , $portion_uids
            )
        );
        $whole_train_overtaken = !in_array(false, $overtaken_portions, true);
        $day_offset = $timestamp->setTime(0, 0, 0)->diff($this->boardDate->toDateTimeImmutable())->days;
?>
                <tr data-timestamp="<?= html($timestamp->getTimestamp()) ?>">
                    <td class="time <?= 
                        $this->connectingTime === null || !$this->station instanceof Station 
                            ? '' 
                            : ($service_call->isValidConnection($this->connectingTime, $this->connectingToc ?? null) ? 'valid_connection' : 'invalid_connection') 
                    ?> <?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>">
                        <?= 
                            show_time($timestamp, $this->boardDate, $this->getServiceLink($service_call))
                            . (in_array(Activity::REQUEST_STOP, $service_call->call->activities) ? '<abbr title="request stop">x</abbr>' : '')
                        ?>
                    </td>
                    <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= $this->showFacilities($service_call) ?></td>
                    <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= html($service_call->call->platform) ?></td>
                    <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><?= $this->showToc($service_call->toc) ?></td>
                    <td class="<?= $whole_train_overtaken ? 'overtaken' : ''?>" rowspan="<?= html($portions_count) ?>"><a href="<?= html($this->getServiceLink($service_call)) ?>"><?= html(substr($service_call->serviceProperty->rsid, 0, 6)) ?></a></td>
<?php
        foreach ($portion_uids as $i => $uid) {
            if ($i > 0) {
?>
                </tr>
                <tr>
<?php
            }
?>
                    <td class="destination <?= $overtaken_portions[$uid] ? 'overtaken' : '' ?>"><?= html($destinations[$uid]->location->getShortName()) ?></td>
                    <td class="<?= $overtaken_portions[$uid] ? 'overtaken' : '' ?>"><?=                        
                        implode(
                            ', '
                            , array_map(
                                function(ServiceCallWithDestination $service_call): string { 
                                    $station = $service_call->call->location;
                                    $link = $this->getArrivalLink($service_call);
                                    return sprintf(
                                        $link === null ? '<span class="%1$s">%3$s (%4$s%5$s)</span>' : '<span class="%s"><a href="%s">%s</a> (%s%s)</span>'
                                        , $station->crsCode !== null && $station->crsCode === $this->destination?->crsCode ? 'destination' : ''
                                        , html($link)
                                        , html($station->getShortName())
                                        , show_time($service_call->timestamp, $this->boardDate)
                                        , in_array(Activity::REQUEST_STOP, $service_call->call->activities) ? '<abbr title="request stop">x</abbr>' : ''
                                    );
                                }
                                , array_filter(
                                    $this->arrivalMode ? $service_call->precedingCalls : $service_call->subsequentCalls
                                    , fn(ServiceCallWithDestination $service_call) : bool =>
                                        in_array($uid, array_keys($this->arrivalMode ? $service_call->origins : $service_call->destinations), true)
                                )
                            )
                        )
                    ?></td>
<?php
        }
?>
                </tr>
<?php
        $previous_timestamp = $timestamp;
    }
?>
            </tbody>
        </table>
        <footer>
            Data updated: <?= $this->generated ?>
        </footer>
<?php
}
?>
    </body>
</html>