<?php
declare(strict_types=1);

use Metroapps\NationalRailTimetable\Views\Components\FixedLink;
use function Metroapps\NationalRailTimetable\Views\show_time;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var FixedLink $this */

if (!empty($this->fixedLinks)) {
    $fixed_link_time = $this->query->getFixedLinkDepartureTime();
    $query = $this->query;
    $station = $query->station;
?>
<table id="fixed_links">
    <thead>
        <tr><th colspan="6">
                Fixed links
                <?= html(
                    $fixed_link_time !== null
                        ? 'as of ' . $fixed_link_time->format('Y-m-d H:i')
                        : 'on ' . $this->date)
                ?>
            </th></tr>
        <tr>
            <th><?= html($query->arrivalMode ? 'Transfer from' : 'Transfer to') ?></th>
            <th>Mode</th>
            <th>From</th>
            <th>To</th>
            <th>Minutes</th>
<?php
    if ($fixed_link_time !== null) {
?>
    <th><?= $query->arrivalMode ? 'Departure' : 'Arrival' ?></th>
<?php
    }
?>
        </tr>
    </thead>
    <tbody>
<?php
    foreach ($this->fixedLinks as $link) {
        if ($fixed_link_time) {
            $kgx_hack = $station->crsCode === 'KGX' && in_array('STP', [$link->destination->crsCode, $link->origin->crsCode], true)
                || $station->crsCode === 'STP' && in_array('KGX', [$link->destination->crsCode, $link->origin->crsCode], true);
            $departure_time = $kgx_hack && $query->connectingTime !== null
                ? $query->arrivalMode ? $query->connectingTime->sub(new DateInterval('PT5M')) : $query->connectingTime->add(new DateInterval('PT5M'))
                : $fixed_link_time;
            $arrival_time = $link->getArrivalTime($departure_time, $query->arrivalMode);
        }
?>
        <tr>
            <td class="destination">
                <a href="<?= html($this->getUrl($link, $departure_time ?? null)) ?>">
                    <?= html(($query->arrivalMode ? $link->origin : $link->destination)->getShortName()) ?>
                </a>
            </td>
            <td><?= html($link->mode) ?></td>
            <td><?= html($link->startTime) ?></td>
            <td><?= html($link->endTime) ?></td>
            <td><?= html($link->transferTime) ?></td>
            <?php
            if ($fixed_link_time !== null) {
                ?>
                <td class="time"><?= show_time($arrival_time, $this->date) ?></td>
                <?php
            }
            ?>
        </tr>
<?php
    }
?>
    </tbody>
</table>
<?php
}
?>