<?php
declare(strict_types=1);

use Metroapps\NationalRailTimetable\Views\Components\Footer;

/** @var Footer $this */
?>
<footer>
<?php
if ($this->generated !== null) {
?>
    <p>
        Data updated: <?= $this->generated ?><br/>
    </p>
<?php
}
?>
    <div id="logo_container">
        <a href="https://www.nationalrail.co.uk"><img id="nre_logo" src="/images/NRE_Powered_logo.png" alt="Powered by National Rail Enquiries" /></a>
    </div>
    <p>© 2022 Michael Tsang &amp; Metroapps Limited. Licensed under AGPL-3.0 or later. <a href="https://github.com/metroapps/national_rail_timetable/">Source available on Github.</a></p>
</footer>
