<footer>
    <p>
        Data updated: <?= $this->generated ?><br/>
    </p>
    <div id="logo_container">
        <a href="https://www.nationalrail.co.uk"><img id="nre_logo" src="/images/NRE_Powered_logo.png" alt="Powered by National Rail Enquiries" /></a>
    </div>
    <p>© 2022 Michael Tsang. Licensed under AGPL-3.0 or later. <a href="https://github.com/miklcct/national_rail_timetable/">Source available on Github.</a></p>
</footer>
