<?php
declare(strict_types = 1);

use Miklcct\RailOpenTimetableData\Models\Station;
use Metroapps\NationalRailTimetable\Views\Components\Form;
use Metroapps\NationalRailTimetable\Views\ViewMode;
use function Miklcct\RailOpenTimetableData\get_all_tocs;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var Form $this */
if ($this->errorMessage !== null) {
?>
<p class="error"><?= html($this->errorMessage) ?></p>
<?php
}

$query = $this->query?->toArray() ?? [];
?>
<form action="board.php" method="GET">
    <datalist id="stations">
<?php
foreach ($this->stations as $station) {
    $easting_northing = $station instanceof Station
        ? sprintf('data-easting="%d" data-northing="%d"', $station->easting, $station->northing)
        : '';
?>
        <option <?= $easting_northing ?> value="<?= html($station->getCrsCode()) ?>"><?= html($station->name) ?></option>
<?php
}
?>
    </datalist>
    <p>
        Show
<?php
foreach (['departures', 'arrivals'] as $mode) {
?>
        <label>
            <input type="radio" name="mode" value="<?= html($mode) ?>" <?= ($query['mode'] ?? 'departures') === $mode ? 'checked = "checked"' : ''?>/>
            <?= html($mode) ?>
        </label>
<?php
}
?>
        <label>at: <input autocomplete="off" list="stations" required="required" type="text" name="station" size="26" value="<?= html($query['station'] ?? null)?>" placeholder="Full name or CRS code"/></label><br/>
        <label>only trains calling at (optional):
<?php
for ($i = 0; $i < 5; ++$i) {
?>
            <input autocomplete="off" list="stations" type="text" name="filter[]" size="3" value="<?= html($query['filter'][$i] ?? null) ?>"/>
<?php
}
?>
        </label><br/>
        <label>but not at (optional):
            <?php
            for ($i = 0; $i < 5; ++$i) {
                ?>
                <input autocomplete="off" list="stations" type="text" name="inverse_filter[]" size="3" value="<?= html($query['inverse_filter'][$i] ?? null) ?>"/>
                <?php
            }
            ?>
        </label><br/>
        <label>on (leave empty for today)
            <input type="date"
                   name="date"
                   value="<?= html($query['date'] ?? null) ?>"
                   min="<?= html((new DateTimeImmutable('-7 days'))->format('Y-m-d')) ?>"
                   max="<?= html((new DateTimeImmutable('+84 days'))->format('Y-m-d')) ?>"
            />
        </label>
    </p>
    <p>
        <label>Show valid connections at:
            <input
                type="datetime-local"
                name="connecting_time"
                value="<?= html($query['connecting_time'] ?? null) ?>"
                min="<?= html(substr((new DateTimeImmutable('today -7 days'))->format('c'), 0, 16)) ?>"
                max="<?= html(substr((new DateTimeImmutable('today +85 days'))->format('c'), 0, 16)) ?>"
            />
        </label>
        <label>from TOC:
            <select name="connecting_toc">
                <option></option>
<?php
foreach (get_all_tocs() as $code => $name) {
?>
                <option value="<?= html($code) ?>" <?=
                $code === ($query['connecting_toc'] ?? null) ? 'selected="selected"' : ''
                ?>><?= html($name) ?></option>
<?php
}
?>
            </select>
        </label>
    </p>
    <p>
        <label>Show permanent timetable instead of actual timetable: <input type="checkbox" name="permanent_only" value="1" <?= !empty($query['permanent_only']) ? 'checked="checked"' : '' ?>/></label><br/>
    </p>
    <p>
<?php
if ($this->viewMode === ViewMode::TIMETABLE) {
?>
        <button type="submit" formaction="timetable.php">Show timetable</button>
<?php
}
?>
        <button type="submit">Show board</button>
<?php
if ($this->viewMode !== ViewMode::TIMETABLE) {
?>
        <button type="submit" formaction="timetable.php">Show timetable</button>
<?php
}
?>
        <a href="/help.xhtml">Usage help</a>
    </p>
</form>
<p id="permanent_warning">Warning: This website shows the scheduled train times without on-the-day alternations. Always check with <a href="https://www.nationalrail.co.uk/">National Rail Enquiries</a> on the day of travel to get up-to-date real time information.</p>
