<?php
declare(strict_types=1);

use Metroapps\NationalRailTimetable\Views\ViewMode;
use Miklcct\RailOpenTimetableData\Models\Station;
use Metroapps\NationalRailTimetable\Views\Components\FixedLink;
use Metroapps\NationalRailTimetable\Views\Components\Footer;
use Metroapps\NationalRailTimetable\Views\Components\Form;
use Metroapps\NationalRailTimetable\Views\ScheduleView;
use function Metroapps\NationalRailTimetable\Views\show_script_tags;
use function Metroapps\NationalRailTimetable\Views\show_toc;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var ScheduleView $this */
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <link rel="stylesheet" href="/common.css" />
<?php
show_script_tags('schedule.ts');
$query = $this->query;
?>
        <title><?= html($this->getTitle()) ?></title>
    </head>
    <body>
        <button id="go_to_top">🔝</button>
        <header class="<?= html($query->permanentOnly ? 'permanent' : '') ?>">
            <?= $this->showHeading() ?>
            <a href="<?= html($this->getViewMode()->getUrl()) ?>">Home</a>
<?php
echo new Form(
    $this->getStreamFactory()
    , $this->stations
    , $this->getViewMode()
    , $this->query
    , null
    , true
);
?>
        </header>
        <main>
            <p id="permanent_warning">Warning: This website shows the scheduled train times without on-the-day alternations. Always check with <a href="https://www.nationalrail.co.uk/">National Rail Enquiries</a> on the day of travel to get up-to-date real time information.</p>
            <?php
if (count($query->filter) === 1) {
?>

        <p><a href="<?= $this->getReverseDirectionLink() ?>">Show return timetable</a></p>
<?php
}
if ($query->permanentOnly) {
?>
        <p id="permanent_warning">Warning: Permanent timetable instead of actual timetable shown</p>
<?php
}
$station = $query->station;
if ($station instanceof Station) {
?>
        <p class="mct_paragraph">Minimum connection time is <span class="time"><?= html(
                    $station->minimumConnectionTime . ($station->minimumConnectionTime === 1 ? ' minute' : ' minutes')) ?></span><?= $station->tocConnectionTimes === [] ? '.' : ', with the exception of the following:' ?></p>
<?php
    if ($station->tocConnectionTimes !== []) {
?>
        <table>
            <thead>
                <tr><th>From</th><th>To</th><th>Minutes</th></tr>
            </thead>
            <tbody>
<?php
        foreach ($station->tocConnectionTimes as $entry) {
?>
                <tr>
                    <td><?= show_toc($entry->arrivingToc) ?></td>
                    <td><?= show_toc($entry->departingToc) ?></td>
                    <td><?= html($entry->connectionTime) ?></td>
                </tr>
<?php
        }
?>
            </tbody>
        </table>
<?php
    }
    echo new FixedLink($this->getStreamFactory(), $this->fixedLinks, $this->query, $this->date, $this->getUrl());
}
echo $this->innerView;
?>
        </main>
<?php
echo new Footer($this->getStreamFactory(), $this->generated);
?>
    </body>
</html>