<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Views\Components\Footer;
use Miklcct\NationalRailTimetable\Views\Components\Form;
use Miklcct\NationalRailTimetable\Views\ScheduleFormView;
use function Miklcct\NationalRailTimetable\Views\show_script_tags;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var ScheduleFormView $this */
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <link rel="stylesheet" href="common.css" />
<?php
show_script_tags('schedule_form.ts');
?>
        <title><?= html($this->getTitle()) ?></title>
    </head>
    <body>
<?php
echo new Form($this->getStreamFactory(), $this->stations, $this->getViewMode(), $this->query ?? null, $this->errorMessage ?? null);
?>
        <p>Click a station in the map to fill in the station field:</p>
        <div id="map"></div>
<?php echo new Footer($this->getStreamFactory(), $this->generated); ?>
    </body>
</html>