<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Views\Components\ServiceInformation;
use function Miklcct\NationalRailTimetable\Views\show_service_property_icons;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var ServiceInformation $this */
?>
<tr>
    <td colspan="5" class="train_info">
        <?=
        implode(
            '<br/>'
            , array_filter(
                [
                    $this->showRsidWithPortionDescription($this->serviceProperty->rsid)
                    , html(
                    implode(
                        ', '
                        , array_filter(
                            [
                                $this->serviceProperty->trainCategory->getDescription(),
                                $this->serviceProperty->identity !== '' ? 'ID ' . $this->serviceProperty->identity : '',
                                $this->serviceProperty->headcode !== '' ? 'Headcode ' . $this->serviceProperty->headcode : '',
                            ]
                        )
                    )
                ),
                    $this->serviceProperty->doo ? 'Driver-only operated' : '',
                    html(
                        implode(
                            ', '
                            , array_filter(
                                [
                                    $this->serviceProperty->power->getDescription(),
                                    $this->serviceProperty->timingLoad ? 'Class ' . $this->serviceProperty->timingLoad : '',
                                    $this->serviceProperty->speedMph ? html($this->serviceProperty->speedMph . ' mph max') : '',
                                ]
                            )
                        )
                    ),
                    html(
                        implode(
                            ', '
                            , [
                                $this->service->shortTermPlanning->getDescription(),
                                $this->service->period->from->__toString() . ' to ' . $this->service->period->to->__toString(),
                                implode(array_intersect_key(['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'], array_filter($this->service->period->weekdays))),
                            ]
                        )
                    ),
                    show_service_property_icons($this->serviceProperty),
                ]
            )
        )
        ?>
    </td>
</tr>
<tr><th>Station</th><th>Pl.</th><th>Arrive</th><th>Depart</th><th>Notes</th></tr>

