<?php
declare(strict_types=1);

use Metroapps\NationalRailTimetable\Views\Components\AllPortions;
use Metroapps\NationalRailTimetable\Views\ServiceView;
use function Miklcct\RailOpenTimetableData\get_all_tocs;
use function Metroapps\NationalRailTimetable\Views\show_script_tags;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var ServiceView $this */

$service = $this->datedService->service;
$date = $this->datedService->date;
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
<?php
show_script_tags('service.ts');
?>
        <link rel="stylesheet" href="/common.css" />
        <title>
            <?= html($this->getTitle() . ($this->permanentOnly ? ' (permanent timetable)' : '')) ?>
        </title>
    </head>
    <body>
        <h1><?= html($this->getTitle()) ?></h1>
        <p><?= html(get_all_tocs()[$service->toc] ?? '') ?></p>
<?php
if ($this->permanentOnly) {
?>
        <p id="permanent_warning">Warning: Permanent timetable instead of actual timetable shown</p>
<?php
}
?>
        <div id="map"><div id="popup"></div></div>

<?php
echo new AllPortions(
    $this->getStreamFactory()
    , $this->getOriginPortion()->date
    , $this->splitIntoPortions($this->datedService)
    , $this->permanentOnly
    , $this->fromViewMode
);
require __DIR__ . '/footer.phtml';
?>
    </body>
</html>