<?php
declare(strict_types=1);

use Miklcct\NationalRailTimetable\Enums\Activity;
use Miklcct\NationalRailTimetable\Models\Points\HasArrival;
use Miklcct\NationalRailTimetable\Models\Points\HasDeparture;
use Miklcct\NationalRailTimetable\Views\ServiceView;

use function Miklcct\NationalRailTimetable\get_all_tocs;
use function Miklcct\ThinPhpApp\Escaper\html;
use Miklcct\NationalRailTimetable\Models\Service;
use Miklcct\NationalRailTimetable\Views\BoardView;

/** @var ServiceView $this */

/** @var Service $service */
$service = $this->datedService->service;
$date = $this->datedService->date;
$timezone = new DateTimeZone('Europe/London');
?>

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="board.css" />
        <title>
            <?= html($this->getTitle()) ?>
        </title>
    </head>
    <body>
        <h1><?= html($this->getTitle()) ?></h1>
        <p><?= html(get_all_tocs()[$service->toc] ?? '') ?></p>
        <?php
if ($this->permanentOnly) {
?>
        <p id="permanent_warning">Warning: Permanent timetable instead of actual timetable shown</p>
<?php
}

$this->showPortions($this->splitIntoPortions($this->datedService));
?>
    </body>
</html>