<?php
declare(strict_types = 1);

use Miklcct\NationalRailTimetable\Models\ServiceCallWithDestination;
use Miklcct\NationalRailTimetable\Views\TimetableView;

use function Miklcct\NationalRailTimetable\get_all_tocs;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var TimetableView $this */
?>
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="common.css" />
        <link rel="stylesheet" href="timetable.css" />
        <title>Timetable</title>
    </head>
    <body>
<?php
foreach ($this->timetables as $timetable) {
    ['stations' => $stations, 'calls' => $calls] = $timetable;

    $get_colspan = function(array $array, int $i) use ($calls) {
        $call = $array[$i];
        $colspan = 0;
        while (isset($array[$i]) && $array[$i]->uid === $call->uid) {
            ++$colspan;
            ++$i;
        }
        return $colspan;
    }
    /** @var Location[] $stations */
    /** @var ServiceCallWithDestination[][] $calls */
?>
        <section>
            <h1>Trains toward <?= html(implode(', ', $this->getGroupDestinations($timetable))) ?></h1>
            <div class="container">
                <table>
                    <thead>
                        <tr>
                            <th class="station_column">TOC</th>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        /** @var ServiceCallWithDestination $call */
        $call = $calls[0][$i];
        $colspan = $get_colspan($calls[0], $i);
        $i += $colspan;
?>
                            <th class="service" colspan=<?= $colspan ?>>
                                <abbr title="<?= html(get_all_tocs()[$call->toc]) ?>"><?= html($call->toc) ?></abbr>
                            </th>
<?php
    }
?>
                        </tr>
                        <tr>
                            <td class="station_column">Headcode</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        /** @var ServiceCallWithDestination $call */
        $call = $calls[0][$i];
        $colspan = $get_colspan($calls[0], $i);
        $i += $colspan;
?>
                            <td colspan=<?= $colspan ?>><?= html($call->serviceProperty->headcode) ?></td>
<?php
    }
?>
                        </tr>
                        <tr>
                            <td class="station_column">Destination</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        /** @var ServiceCallWithDestination $call */
        $call = $calls[0][$i];
        foreach ($call->destinations as $destination) {
?>
                            <td><abbr title="<?= html($destination->location->getShortName()) ?>"><?= html($destination->location->crsCode) ?></abbr></td>
<?php
            ++$i;
        }
    }
?>
                        </tr>
                        <tr>
                            <td class="station_column">Facilities</td>
<?php
    $i = 0;
    while (isset($calls[0][$i])) {
        /** @var ServiceCallWithDestination $call */
        $call = $calls[0][$i];
        $colspan = $get_colspan($calls[0], $i);
        $i += $colspan;
?>
                            <td colspan=<?= $colspan ?>><?= $call->mode->showIcon() . $call->serviceProperty->showIcons() ?></td>
<?php
    }
?>
                        </tr>
<?php
    foreach ($stations as $i => $station) {
        if ($i === 1) {
?>
                    </thead>
                    <tbody>
<?php
        }
?>
                        <tr class="<?= $i === 0 ? 'origin' : '' ?> <?= $i !== 0 && in_array($station->crsCode, $this->filterCrs, true) ? 'destination' : '' ?>">
                            <td class="station_column"><?= html($station->getShortName()) ?></td>
<?php
        $j = 0;
        while (isset($calls[0][$j])) {
            if (!isset($calls[$i][$j])) {
                ++$j;
?>
                            <td></td>
<?php
            } else {
                $call = $calls[$i][$j];
                $colspan = $get_colspan($calls[$i], $j);
                $j += $colspan;
?>
                           <td colspan=<?= $colspan ?>><?= html($call->timestamp->format('H:i'))?></td>
<?php
            }
        }
?>
                        </tr>
<?php
    }
?>
                    </tbody>
                </table>
            </div>
        </section>
<?php
}
?>
    </body>
</html>