<?php
declare(strict_types = 1);

use Miklcct\NationalRailTimetable\Controllers\BoardQuery;
use Miklcct\NationalRailTimetable\Models\DepartureBoard;
use Miklcct\NationalRailTimetable\Models\Location;
use Miklcct\NationalRailTimetable\Models\LocationWithCrs;
use Miklcct\NationalRailTimetable\Models\ServiceCallWithDestination;
use Miklcct\NationalRailTimetable\Models\Timetable;
use Miklcct\NationalRailTimetable\Views\ServiceView;
use Miklcct\NationalRailTimetable\Views\TimetableView;
use Miklcct\NationalRailTimetable\Views\ViewMode;
use function Miklcct\NationalRailTimetable\Views\show_activities;
use function Miklcct\NationalRailTimetable\Views\show_time;
use function Miklcct\ThinPhpApp\Escaper\html;

/** @var TimetableView $this */
?>
<?php
    /** @var DepartureBoard $board */
    foreach ($this->boards as $board) {
        $timetable = Timetable::generateFromBoard($board);
        $stations = $timetable->stations;
        /** @var ServiceCallWithDestination[][] $calls */
        $calls = $timetable->calls;

        $get_colspan = static function(array $array, int $i) {
            $call = $array[$i];
            $colspan = 0;
            while (
                isset($array[$i])
                && $array[$i]->uid === $call->uid
                && $array[$i]->timestamp == $call->timestamp
            ) {
                ++$colspan;
                ++$i;
            }
            return $colspan;
        };
        $via = $board->getDestinations(true);
        $destinations = $board->getDestinations();
        $stations_from = 1;
        $stations_to = count($stations) - 1;
        if ($this->query->filter) {
            if ($this->query->arrivalMode) {
                while (
                    !in_array(
                        $stations[$stations_from]->getCrsCode()
                        , array_map(static fn(LocationWithCrs $location) => $location->getCrsCode(), $this->query->filter)
                        , true
                    )
                ) {
                    ++$stations_from;
                }
            } else {
                while (
                    !in_array(
                        $stations[$stations_to]->getCrsCode()
                        , array_map(static fn(LocationWithCrs $location) => $location->getCrsCode(), $this->query->filter)
                        , true
                    )
                ) {
                    --$stations_to;
                }
            }
        }
?>
        <section>
            <h2>Trains
                <?= $this->query->arrivalMode && $destinations ? ' from ' . html(implode(', ', array_map(static fn(Location $location) => $location->getShortName(), $destinations))) : '' ?>
                <?= $via ? ' via ' . html(implode(', ', array_map(static fn(Location $location) => $location->getShortName(), $via))) : '' ?>
                <?= !$this->query->arrivalMode && $destinations ? ' towards ' . html(implode(', ', array_map(static fn(Location $location) => $location->getShortName(), $destinations))) : '' ?>
            </h2>
            <div class="container">
                <table class="timetable">
                    <thead>
                        <tr class="info">
                            <th class="station_column">TOC</th>
<?php
        $i = 0;
        while (isset($calls[0][$i])) {
            $call = $calls[0][$i];
            $colspan = $get_colspan($calls[0], $i);
?>
                            <th class="service" colspan=<?= $colspan ?> data-timestamp="<?= html($calls[0][$i]->timestamp->getTimestamp()) ?>">
                                <?= $this->showToc($call->toc) ?>
                            </th>
<?php
            $i += $colspan;
        }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Headcode</td>
<?php
        $i = 0;
        while (isset($calls[0][$i])) {
            /** @var ServiceCallWithDestination $call */
            $call = $calls[0][$i];
            $colspan = $get_colspan($calls[0], $i);
            $i += $colspan;
?>
                            <td colspan=<?= $colspan ?>><?= html($call->serviceProperty->headcode) ?></td>
<?php
        }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Origin</td>
<?php
        $i = 0;
        while (isset($calls[0][$i])) {
            $call = $calls[0][$i];
            if ($this->query->arrivalMode) {
                foreach ($call->origins as $origin) {
                    $location = $origin->location;
                    if (!$location instanceof LocationWithCrs) {
                        $location = null;
                    }
?>
                            <td><abbr title="<?=
                                html($location?->getShortName()) ?>"><?= html($location?->getCrsCode()) ?></abbr></td>
<?php
                    ++$i;
                }
            } else {
                $colspan = $get_colspan($calls[0], $i);
?>
                            <td colspan="<?= $colspan ?>">
<?php
                foreach ($call->origins as $origin) {
                    $location = $origin->location;
                    if (!$location instanceof LocationWithCrs) {
                        $location = null;
                    }
?>
                    <abbr title="<?= html($location?->getShortName()) ?>"><?= html($location?->getCrsCode()) ?></abbr>
<?php
                }
?>
                            </td>
<?php
                $i += $colspan;
            }
        }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Destination</td>
<?php
        $i = 0;
        while (isset($calls[0][$i])) {
            $call = $calls[0][$i];
            if (!$this->query->arrivalMode) {
                foreach ($call->destinations as $destination) {
                    $location = $destination->location;
                    if (!$location instanceof LocationWithCrs) {
                        $location = null;
                    }
?>
                            <td><abbr title="<?=
                                html($location?->getShortName()) ?>"><?= html($location?->getCrsCode()) ?></abbr></td>
<?php
                    ++$i;
                }
            } else {
                $colspan = $get_colspan($calls[0], $i);
?>
                            <td colspan="<?= $colspan ?>">
<?php
                foreach ($call->destinations as $destination) {
                    $location = $destination->location;
                    if (!$location instanceof LocationWithCrs) {
                        $location = null;
                    }
?>
                    <abbr title="<?= html($location?->getShortName()) ?>"><?= html($location?->getCrsCode()) ?></abbr>
<?php
                }
?>
                            </td>
<?php
                $i += $colspan;
            }
        }
?>
                        </tr>
                        <tr class="info">
                            <td class="station_column">Facilities</td>
<?php
        $i = 0;
        while (isset($calls[0][$i])) {
            /** @var ServiceCallWithDestination $call */
            $call = $calls[0][$i];
            $colspan = $get_colspan($calls[0], $i);
            $i += $colspan;
?>
                            <td colspan=<?= $colspan ?>><?= $this->showFacilities($call) ?></td>
<?php
        }
?>
                        </tr>
<?php
        $show_platforms = function () use ($get_colspan, $calls) {
?>
            <tr class="info">
                <td class="station_column">Platform</td>
<?php
            $i = 0;
            while (isset($calls[0][$i])) {
                /** @var ServiceCallWithDestination $call */
                $call = $calls[0][$i];
                $colspan = $get_colspan($calls[0], $i);
                $i += $colspan;
?>
                <td colspan=<?= $colspan ?>><?= html($call->call->platform) ?></td>
<?php
            }
?>
            </tr>
<?php
        };
        if (!$this->query->arrivalMode) {
            $show_platforms();
        }
?>
<?php
        foreach (array_merge([0], range($stations_from, $stations_to)) as $i) {
            $station = $stations[$i];
            if ($i === 0 && $this->query->arrivalMode) {
?>
                    </thead>
                    <tfoot>
<?php
            } elseif ($i === $stations_from) {
                if ($this->query->arrivalMode) {
                    $show_platforms();
?>
                    </tfoot>
<?php
                } else {
?>
                    </thead>
<?php
                }
?>
                    <tbody>
<?php
            }
?>
                        <tr class="<?= $i === 0 ? 'origin' : '' ?> <?= $i !== 0 && in_array($station->getCrsCode(), array_map(static fn(LocationWithCrs $location) => $location->getCrsCode(), $this->query->filter), true) ? 'destination' : '' ?>">
                            <td class="station_column">
                                <div class="station_name">
                                    <span>

<?php
            if ($i !== 0) {
?>
                                        <a href="<?= html((new BoardQuery($this->query->arrivalMode, $this->query->station, [$station], $this->query->inverseFilter, $this->query->date, $this->query->connectingTime, $this->query->connectingToc, $this->query->permanentOnly))->getUrl(
                                            TimetableView::URL
                                        )) ?>">
<?php
            }
?>
                                            <?= html($station->getShortName()) ?>
<?php
            if ($i !== 0) {
?>
                                        </a>
<?php
            }
            $is_arrival = $this->query->arrivalMode === ($i === 0);
?>
                                    </span>
                                    <abbr class="departure_arrival" title="<?= html($is_arrival ? 'arrival' : 'departure') ?>"><?= html($is_arrival ? 'a' : 'd') ?></abbr>
                                </div>
                            </td>
<?php
            $j = 0;
            while (isset($calls[0][$j])) {
                $connection_class = $this->query->connectingTime !== null
                    ? $calls[0][$j]->isValidConnection($this->query->connectingTime, $this->query->connectingToc)
                    ? 'valid_connection' : 'invalid_connection'
                    : '';
                if (
                    $i !== 0
                    && isset($calls[$i][$j])
                    && $board->isCallOvertaken(
                        $calls[0][$j]
                        , $calls[$i][$j]
                    )
                ) {
                    $connection_class .= ' overtaken';
                }
                if (!isset($calls[$i][$j])) {
?>
                            <td class="<?= $connection_class ?>"></td>
<?php
                    ++$j;
                } else {
                    $call = $calls[$i][$j];
                    $colspan = $get_colspan($calls[$i], $j);
                    $link = $i === 0
                        ? ServiceView::getServiceUrl($call->uid, $call->date, $this->query->permanentOnly, ViewMode::TIMETABLE)
                        : $this->getArrivalLink($calls[$i][$j]);
?>
                           <td class="<?= $connection_class ?>" colspan=<?= $colspan ?>><?= show_time($call->timestamp, $this->date, $link) . show_activities($call->call->activities) ?></td>
<?php
                    $j += $colspan;
                }
            }
?>
                        </tr>
<?php
        }
?>
                    </tbody>
                </table>
            </div>
        </section>
<?php
    }
?>